c_in: 512
s_c_h: 128
d_c_h: 128
c_bank: 128
c_latent: 128
c_cond: 128
s_kernel_size: 3
d_kernel_size: 5
bank_size: 8 
bank_scale: 1
s_enc_n_conv_blocks: 6
s_enc_n_dense_blocks: 2
d_enc_n_conv_blocks: 6
d_enc_n_dense_blocks: 0
s_subsample: [1, 2, 1, 2, 1, 2]
d_subsample: [1, 2, 1, 2, 1, 2]
dec_n_conv_blocks: 6
dec_n_dense_blocks: 2
dec_n_mlp_blocks: 4
upsample: [2, 1, 2, 1, 2, 1]
gen_act: 'relu'
dis_act: 'lrelu'
dropout_rate: 0.5
dis_c_h: 128
dis_kernel_size: 3
dis_n_conv_blocks: 5
dis_subsample: [2, 2, 2, 2, 2]
dis_n_dense_layers: 2
dis_d_h: 512
dis_ins_norm: True
dis_dropout_rate: 0.3
segment_size: 128
frame_size: 1
batch_size: 8
shuffle: True
gen_lr: 0.0001
dis_lr: 0.0004
beta1: 0
beta2: 0.999
ema_weight: 0.999
amsgrad: False
init_lambda_rec: 10
final_lambda_rec: 10
lambda_srec: 1
lambda_dis: 1
lambda_kl: 0.01
lambda_gp: 10 
weight_decay: 0.0001
instance_noise: True
gaussian_std: 0.15
grad_norm: 1
ae_steps: 1
dis_steps: 1
srec_sched_iters: 0
dis_sched_iters: 30000
rec_sched_iters: 30000
noise_sched_iters: 100000
sample_rate: 24000
sn: False
use_dummy: False
use_mismatch: False
